"""Initial migration

Revision ID: 9f3c0bc602b7
Revises: 
Create Date: 2021-06-13 23:26:00.479653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3c0bc602b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_patients',
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id_hospital', 'id_patient')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_patients')
    op.drop_table('patient')
    op.drop_table('hospital')
    # ### end Alembic commands ###
